name: matrix demo
on:
  push:
  # workflow_dispatch:

jobs:
  deploy:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}